import{a as d,i as l}from"./assets/vendor-98a16590.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const c of r.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&i(c)}).observe(document,{childList:!0,subtree:!0});function a(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerpolicy&&(r.referrerPolicy=e.referrerpolicy),e.crossorigin==="use-credentials"?r.credentials="include":e.crossorigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function i(e){if(e.ep)return;e.ep=!0;const r=a(e);fetch(e.href,r)}})();d.defaults.headers.common["x-api-key"]="live_XaDOlWdJOSUjjdvdR99bU6UBO5wwUvUP0vR0gjPrtVs2YssEWHnbGu1nmo6OGOG0";async function u(){return await d.get("https://api.thecatapi.com/v1/breeds").then(t=>t.data)}async function m(t){return await d.get(`https://api.thecatapi.com/v1/images/search?breed_ids=${t}`).then(o=>o.data)}const n={breedSelect:document.querySelector(".breed-select"),catInfo:document.querySelector(".cat-info"),loader:document.querySelector(".loader"),title:document.querySelector(".animate__animated")};function s(t,o){t.classList.toggle("hidden",!o)}n.title.classList.add("animate__animated","animate__zoomInDown");n.title.addEventListener("animationend",()=>{h()});s(n.breedSelect,!1);s(n.loader,!0);async function f(){try{s(n.loader,!0),s(n.catInfo,!1);const t=n.breedSelect.value,o=await m(t);p(o)}catch{l.show({position:"topRight",message:"Oops! Something went wrong! Try reloading the page!"})}s(n.loader,!1)}function p(t){const o=t[0].url,a=t[0].breeds[0],i=`<div class="card">
  <img class="img" src="${o}" alt="${a.name}"/>
      <div class="info">
        <h2 class="name">${a.name}</h2>
        <p><span class="description">Description: </span> ${a.description}</p>
        <p><span class="temperament">Temperament: </span> ${a.temperament}</p>   
       </div>
</div>`;n.catInfo.innerHTML=i,s(n.catInfo,!0)}async function h(){try{const o=(await u()).map(({id:a,name:i})=>`<option value="${a}">${i}</option>`).join("");n.breedSelect.innerHTML=o,s(n.breedSelect,!0),n.breedSelect.addEventListener("change",f)}catch{l.show({position:"topRight",message:"Oops! Something went wrong! Try reloading the page!"})}s(n.loader,!1)}
//# sourceMappingURL=commonHelpers.js.map
